<?php
// $api=VVi5Ut2rW5NiUlBTeqEWpft7
$api="rzp_test_PZyeTH8RQjyPxN";
include 'cart_main.php';

//classes import karra rahe hai phpmailer , smtp , exception ; har file ka namespace access kar rahe hai
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

require 'Exception.php';
require 'SMTP.php';
require 'PHPMailer.php';

if(isset($_POST['submit'])){
    $mail = new PHPMailer(true);

    $pname=$_POST['name'];
    $pmail=$_POST['email'];
    $paddress=$_POST['address'];

    try {
        //Server settings
        // $mail->SMTPDebug = SMTP::DEBUG_SERVER;                      //Enable verbose debug output
        $mail->isSMTP();                                            //Send using SMTP
        $mail->Host       = 'smtp.gmail.com';                     //Set the SMTP server to send through
        $mail->SMTPAuth   = true;                                   //Enable SMTP authentication
        $mail->Username   = 'aditya.as@somaiya.edu';                     //SMTP username
        $mail->Password   = 'Aditya@123';                               //SMTP password
        $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;            //Enable implicit TLS encryption
        $mail->Port       = 465;                                    //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`
    
        //Recipients
        $mail->setFrom('aditya.as@somaiya.edu', 'ADITYA');
    
    
    
    
    
        $mail->addAddress($pmail);     //Add a recipient
        
        
        
        
        
        
        
        
        
        // $mail->addAddress('ellen@example.com');               //Name is optional
        // $mail->addReplyTo('info@example.com', 'Information');
        // $mail->addCC('cc@example.com');
        // $mail->addBCC('bcc@example.com');
    
        // //Attachments
        // $mail->addAttachment('/var/tmp/file.tar.gz');         //Add attachments
        // $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    //Optional name
    
        //Content
        $mail->isHTML(true);                                  //Set email format to HTML
        $mail->Subject = 'THANKS FOR ORDERING';
        $mail->Body    = "Thanks for ordering $pname .<br>Your order is shipped and you will recieve your order at $paddress ";
        // $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
    
        $mail->send();
        // echo "<script>alert('Message has been sent')</script>";
    } catch (Exception $e) {
        // echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
    }
}














?>

<style>
  .razorpay-payment-button{display : none;}
</style>






























































<form action="http://localhost/gym/thankyou.php" method="POST">
  <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key=<?php echo $api; ?> // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount=<?php echo $totalsum*100; ?> // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id=<?php echo 'OID'.rand(10,100) ?>// Replace with the order_id generated by you in the backend.
    data-buttontext=""
    data-name="Muscle Manufacturer"
    data-description="COPYRIGHT BY ADITYA"
    
    data-prefill.name="<?php  echo $_POST['name']; ?>"
    data-prefill.email="<?php  echo $_POST['email']; ?>"
    data-prefill.contact="<?php  echo $_POST['phone']; ?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>

































<script type="text/javascript">
  $(document).ready(function()
  {
    $('.razorpay-payment-button').click();
  }
  )
</script>